library("dplyr")
library("xlsx")
library("lubridate")
library("tidyr")
setwd("C:/Sammy/R/Test/test/Data")
dt <- as.POSIXlt(Sys.Date())
cut_off_dt <- as.Date(floor_date(dt %m-% months(36),"month"))

ccd_sample <- read.xlsx("ccdata_v1.xlsx", sheetName = "ccd", header=T, colIndex = c(1:2,4:7), endRow = 100)
classes <- c("character","Date","character","integer","character","character")
ccd <- read.xlsx("ccdata_v1.xlsx", sheetName = "ccd", header=T, colIndex = c(1:2,4:7), colClasses = classes)
ccd <- filter(ccd,DATE >=cut_off_dt,STATUS=="SUCCESS")
c <- tbl_df(ccd);rm(ccd)

c_crdt <- group_by(c,CREDITCARDNO,TRANSCTIONTYPE)
summ <- summarize(c_crdt, amount=sum(AMOUNT))
summ <- as.data.frame(summ)
summ2 <- spread(summ,TRANSCTIONTYPE,amount)
write.xlsx(summ2,"summ2.xlsx",sheetName = "Summary",col.names = T)